spring.application.name=motorenter
spring.datasource.url=jdbc:postgresql://localhost:5432/motorenter
spring.datasource.username=postgres
spring.datasource.password=Ripazha4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true